# Sample public application.yml to be used by Spring Cloud Config Server

application:
    message: Dan was here
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 20000

security:
  oauth2:
    resource:
      user-info-uri: http://gateway/uaa/users/current


spring:
  sleuth:
    sampler:
      probability: 1
